name: Android CI
on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  lint:
    name: Perform Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - uses: actions/cache@v3
        name: Caching Gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v3
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html
  debug-apk:
    needs: [ lint ]
    name: Generate Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - uses: actions/cache@v3
        name: Caching Gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run gradle tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    needs: [ lint ]
    name: Build Release signed APK and Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - uses: actions/cache@v3
        name: Caching Gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate file name env var
        run: |
          VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)
          DATE=$(date +'%d.%m.%Y')
          BRANCH_NAME=${GITHUB_REF##*/}
          MESSAGE=$(cat << EOF
          AppName-release-${VERSION_NAME}-${BRANCH_NAME}-${DATE}
          EOF)
          echo OUTPUT_NAME=$MESSAGE >> $GITHUB_ENV

      - name: Run gradle tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Rename APK
        run: mv "./app/build/outputs/apk/release/app-release.apk" "./app/build/outputs/apk/release/${{ env.OUTPUT_NAME }}.apk"

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: ${{steps.sign_app_apk.outputs.signedReleaseFile}}

      - name: Build release AAB
        run: bash ./gradlew bundleRelease --stacktrace

      - name: Rename AAB
        run: mv "./app/build/outputs/bundle/release/app-release.aab" "./app/build/outputs/bundle/release/${{ env.OUTPUT_NAME }}.aab"

      - name: Sign Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app_bundle
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Signed AAB
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: ${{steps.sign_app_bundle.outputs.signedReleaseFile}}
