name: Android CI
on:
  push:
    branches:
      - release/*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    name: Perform Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - uses: actions/cache@v3
        name: Caching Gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v3
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  debug-apk:
    needs: [ lint ]
    name: Generate Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - uses: actions/cache@v3
        name: Caching Gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run gradle tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  build-release:
    needs: [ lint ]
    name: Build Release signed APK and Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - uses: actions/cache@v3
        name: Caching Gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate file name env var
        run: |
          VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)
          MESSAGE=$(cat << EOF
          NutriLog-release-${VERSION_NAME}
          EOF)
          echo OUTPUT_NAME=$MESSAGE >> $GITHUB_ENV

      - name: Run gradle tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app_apk
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: ${{steps.sign_app_apk.outputs.signedReleaseFile}}

      - name: Build release AAB
        run: bash ./gradlew bundleRelease --stacktrace

      - name: Sign Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app_bundle
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload Signed AAB
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: ${{steps.sign_app_bundle.outputs.signedReleaseFile}}

  release:
    name: Create Release
    needs: [ build-release ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - uses: actions/cache@v3
        name: Caching Gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate tag name and release name env var
        run: |
          VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)
          RELEASE_MESSAGE=$(cat << EOF
          Release v${VERSION_NAME}
          EOF)
          TAG_MESSAGE=$(cat << EOF
          release-${VERSION_NAME}
          EOF)
          MESSAGE=$(cat << EOF
          NutriLog-release-${VERSION_NAME}
          EOF)
          echo TAG_NAME=TAG_MESSAGE >> $GITHUB_ENV
          echo RELEASE_NAME=RELEASE_MESSAGE >> $GITHUB_ENV
          echo OUTPUT_NAME=$MESSAGE >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: ./artifacts

      - name: Unzip Artifact
        run: unzip ./artifacts/${{ env.OUTPUT_NAME }}.zip -d ./artifacts

      - name: Upload Release APK and Bundle
        uses: meeDamian/github-release@2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          files: |
            ./artifacts/*.apk
            ./artifacts/*.aab
          allow_override: true
